apiVersion: v1
kind: Pod
metadata:
  name: buggy-app-no-probe
  labels:
    app: buggy
spec:
  containers:
    - name: buggy-container      
      image: captainyun/buggy-node-app:v1.0
      ports:
        - containerPort: 8080
