apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  # 데이터베이스 비밀번호
  SPRING_DATASOURCE_PASSWORD: "pass1234"

  # JWT 서명 비밀키
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET_KEY: "CDIwMSAarj20dJShD7/s5K3a8hvXfNtveJp49YC0eozRUCtqa0ufxnY+9wKDRXuQ5eWY54Stsq9Rkh4O9O/cHQ=="

  # Cloudflare R2 자격증명
  CLOUDFLARE_ACCESS_KEY_ID: "15e54eeb3709a76fe508bb97e9a9b733"
  CLOUDFLARE_SECRET_ACCESS_KEY: "8f9a7713105d93321180fc1bf832869f00a31ad642161a22b7c7a8fc5ac5da52"
